### ISSUE TITLE
Error when using StartTime and EndTime

### ISSUE THREAD

**Issue by jchampagne** [splunk/splunk-reskit-powershell#4] opened 2012-08-02 21:05 UTC
When I use the -StartTime and -EndTime paramenters for the Search-Splunk cmdlet, I get the following reposnse from the server:

Invoke-HTTPPost : Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (400) Bad Request."

**Comment by halr9000** [comment] 2012-08-03 14:08
Confirmed. If you run a search with the -Verbose switch, you can see this:

```
VERBOSE:  [Invoke-HTTPPost] :: $PostString = earliest_time=&search=...
```

Note that no value is being passed to the "earliest_time" key.

I'm not receiving a 400 error, but the search isn't working, either.

**Comment by halr9000** [comment] 2012-08-03 14:10
@jchampagne what version are you running? We pushed a new version the other day. I'm curious to know if you get the same results as I do if you update. Also, please try running with -Verbose. Lots of good info in there.

**Comment by jchampagne** [comment] 2012-08-06 15:51
I'm running 0.2

Here is the output from the command with the verbose switch:

PS C:> Search-Splunk -Search "<REDACTED>" -StartTime "8/6/12 11:00 AM" -EndTime "8/6/12 12:00 PM" -
Verbose
VERBOSE:  [Search-Splunk] :: Starting...
VERBOSE:  [Search-Splunk] :: Building Search Arguments
VERBOSE:  [Search-Splunk] :: Parameters
VERBOSE:  [Search-Splunk] ::  - ComputerName = <REDACTED>
VERBOSE:  [Search-Splunk] ::  - Port         = 8089
VERBOSE:  [Search-Splunk] ::  - Protocol     = https
VERBOSE:  [Search-Splunk] ::  - Timeout      = 10000
VERBOSE:  [Search-Splunk] ::  - Credential   = System.Management.Automation.PSCredential
VERBOSE: Performing operation "Executing search for '<REDACTED>'" on Target "<REDACTED>".
VERBOSE:  [Search-Splunk] :: Setting up Invoke-APIRequest parameters
VERBOSE:  [Search-Splunk] :: Calling Invoke-SplunkAPIRequest @InvokeAPIParams
VERBOSE:  [Invoke-SplunkAPIRequest] :: Starting
VERBOSE:  [Invoke-SplunkAPIRequest] :: Using [byCredential] ParameterSet
VERBOSE:  [Invoke-SplunkAPIRequest] :: Parameters
VERBOSE:  [Invoke-SplunkAPIRequest] ::  - Endpoint     = /services/search/jobs
VERBOSE:  [Invoke-SplunkAPIRequest] ::  - Format       = XML
VERBOSE:  [Invoke-SplunkAPIRequest] ::  - RequestType  = POST
VERBOSE:  [Invoke-SplunkAPIRequest] ::  - ComputerName = <REDACTED>
VERBOSE:  [Invoke-SplunkAPIRequest] ::  - Port         = 8089
VERBOSE:  [Invoke-SplunkAPIRequest] ::  - Protocol     = https
VERBOSE:  [Invoke-SplunkAPIRequest] ::  - Timeout      = 10000
VERBOSE:  [Invoke-SplunkAPIRequest] ::  - FullURL      = https://<REDACTED>:8089/services/search/jobs
VERBOSE:  [Invoke-SplunkAPIRequest] ::  - Credential   = System.Management.Automation.PSCredential
VERBOSE:  [Invoke-HTTPPost] :: Creating POST message
VERBOSE:  [Invoke-HTTPPost] :: $PostString =
latest_time=8%2f6%2f12+12%3a00+PM&earliest_time=&search=search+<REDACTED>&exec_mode=oneshot
VERBOSE:  [Invoke-HTTPPost] :: Using [byCreds] ParameterSet
VERBOSE:  [Invoke-HTTPPost] :: Connecting to URL: https://<REDACTED>:8089/services/search/jobs
VERBOSE:  [Invoke-HTTPPost] :: Sending POST message
VERBOSE:  [Invoke-HTTPPost] :: Closing POST stream
VERBOSE:  [Invoke-HTTPPost] :: Getting Response from POST
VERBOSE:  [Invoke-HTTPPost] :: Error getting response from POST
Invoke-HTTPPost : Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (400) Bad
 Request."
At C:\Users<REDACTED>\Documents\WindowsPowerShell\Modules\splunk\Splunk-Core\Splunk-Core.psm1:587 char:77
-                                     "POST"          { $xml = Invoke-HTTPPost <<<<        @InvokeHTTPParams -Creds $Cr
  edential -Arguments $Arguments }
  - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
  - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-HTTPPost

VERBOSE: <?xml version='1.0' encoding='UTF-8'?>
<response><messages><msg type='FATAL'>Invalid latest_time: latest_time must be after
earliest_time.</msg></messages></response>
VERBOSE: The Splunk API has returned a partial XML document that appears to be an empty set
VERBOSE:  [Invoke-SplunkAPIRequest] :: =========    End   =========
VERBOSE:  [Search-Splunk] :: No Response from REST API. Check for Errors from Invoke-SplunkAPIRequest
VERBOSE:  [Search-Splunk] :: =========    End   =========

**Comment by jchampagne** [comment] 2012-08-06 15:55
Looks like a problem with the order of the parameters:
<response><messages><msg type='FATAL'>Invalid latest_time: latest_time must be after earliest_time.</msg></messages></response>

The query string being generated is:  
latest_time=8%2f6%2f12+12%3a00+PM&earliest_time=&search=search+<REDACTED>&exec_mode=oneshot

**Comment by halr9000** [comment] 2012-08-06 15:56
Oh good, that helps. Looks like the function is passing the latest time argument, but omitting the earliest time as you can see here:
`$PostString = latest_time=8%2f6%2f12+12%3a00+PM&earliest_time=&search=search+&exec_mode=oneshot`
We'll try and fix that as soon as possible.

**Comment by jchampagne** [comment] 2012-08-06 15:57
Thanks!

**Comment by jchampagne** [comment] 2012-08-06 16:48
It actually looks like two problems.

1, in Splunk-Search.psm1, Search-Splunk:

When you're adding values to $SearchParams.Add, line 89 appears to be incorrect:
  "StartTime"   { $SearchParams.Add('earliest_time',$DefaultHostName)   ; continue }
Should be:
  "StartTime"   { $SearchParams.Add('earliest_time',$StartTime)                       ; continue }

2, in Splunk-Core.psm1, Invoke-SplunkAPIRequest:
  The arguments aren't being ordered properly in the POST message

**Comment by halr9000** [comment] 2012-08-06 17:50
Marked to fix in 0.3.

**Comment by toenuff** [comment] 2013-08-21 03:04
Looks like there may be more to this.  I went to fix it for myself based on jchampagne's notes, but it looks like there's more to it than just the order.  I tried to run this:

<pre>Search-Splunk -verbose -starttime (Get-Date).addminutes(-59) 'index=perfmon |stats count by host' </pre>

Here's the relevant part of the error.  It looks like the time format is wrong too:

<pre>
VERBOSE:  [Invoke-HTTPPost] :: Creating POST message
VERBOSE:  [Invoke-HTTPPost] :: $PostString =
earliest_time=08%2f20%2f2013+21%3a51%3a54&search=search+index%3dperfmon+%7cstats+count+by+host&exec_mode=oneshot
VERBOSE:  [Invoke-HTTPPost] :: Using [byCreds] ParameterSet
VERBOSE:  [Invoke-HTTPPost] :: Connecting to URL: http://adwas17:8089/services/search/jobs
VERBOSE:  [Invoke-HTTPPost] :: Sending POST message
VERBOSE:  [Invoke-HTTPPost] :: Closing POST stream
VERBOSE:  [Invoke-HTTPPost] :: Getting Response from POST
VERBOSE:  [Invoke-HTTPPost] :: Error getting response from POST
Invoke-HTTPPost : Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (400) Bad
 Request."
At C:\MSDE\splunk-reskit-powershell\Source\Splunk\Splunk-Core\Splunk-Core.psm1:587 char:77
+                                     "POST"          { $xml = Invoke-HTTPPost <<<<        @InvokeHTTPParams -Creds $Cr
edential -Arguments $Arguments }
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-HTTPPost
VERBOSE: <?xml version='1.0' encoding='UTF-8'?>
<response><messages><msg type='FATAL'>Invalid earliest_time.</msg></messages></response>
VERBOSE: The Splunk API has returned a partial XML document that appears to be an empty set
VERBOSE:  [Invoke-SplunkAPIRequest] :: =========    End   =========
VERBOSE:  [Search-Splunk] :: No Response from REST API. Check for Errors from Invoke-SplunkAPIRequest
VERBOSE:  [Search-Splunk] :: =========    End   =========
</pre>

**Comment by jheiselman** [comment] 2013-08-23 16:13
The problem is in `Invoke-SplunkAPIRequest` in the Splunk-Core.psm1 file. To fix it, we have to cherry pick the search parameter and add it to beginning of the string, remove it from the hashtable, then iterate over the remaining hash entries adding them to them to the `$PostString`.

Starting at line 223:

Change it from

```
    $i = 1

    Write-Verbose " [Invoke-HTTPPost] :: Creating POST message"
    foreach($Argument in $Arguments.Keys)
    {
        if($i -le 1)
        {
            [string]$PostString = "{0}={1}" -f $Argument,[System.Web.HttpUtility]::UrlEncode([string]$Arguments[$Argument])
        }
        else
        {
            [string]$PostString += "&{0}={1}" -f $Argument,[System.Web.HttpUtility]::UrlEncode([string]$Arguments[$Argument])
        }
        $i++
    }


    Write-Verbose " [Invoke-HTTPPost] :: `$PostString = $PostString"
```

to

```
    Write-Verbose " [Invoke-HTTPPost] :: Creating POST message"
    [string]$PostString = "search={0}" -f [System.Web.HttpUtility]::UrlEncode([string]$Arguments['search'])
    $Arguments.Remove('search')
    foreach($Argument in $Arguments.Keys)
    {
        [string]$PostString += "&{0}={1}" -f $Argument,[System.Web.HttpUtility]::UrlEncode([string]$Arguments[$Argument])
    }
```

**Comment by jchampagne** [comment] 2013-10-15 20:31
Jerry,

I ran the code from your fork, but am still getting an error when running a search using StartTime and EndTime.  It looks like the POST message isn't being formatted properly.

VERBOSE:  [Invoke-HTTPPost] :: $PostString =
search=search+index%3dMyIndex+host%3dMyHost&latest_time=10%2f15%2f2013+4%3a05+PM&earliest_time=10%
13+4%3a00+PM&count=5&auto_finalize_ec=5&exec_mode=oneshot

VERBOSE: <?xml version="1.0" encoding="UTF-8"?>
<response>
  <messages>
    <msg type="FATAL">Invalid earliest_time.</msg>
  </messages>
</response>

**Comment by jheiselman** [comment] 2013-10-16 02:27
jchampagne,

I will take a look at this and try to run your query when I get back in the office. It worked in several of my tests and for another guy in my office. The only difference that I can see immediately is that my tests used relative date expressions (i.e. -24h) instead of an absolute date. We may need to detect when the user has specified an absolute date and convert it before adding it to the post parameters.

**Comment by jchampagne** [comment] 2013-10-16 21:11
@jheiselman,

You're right, the relative date expressions work fine.  I never tried them in my "testing", but for production scripts I'd be using realtive expressions anyway...so not a big deal.  Probably still worth addressing at some point I guess.

Thanks for the help!

**Comment by jheiselman** [comment] 2013-10-24 17:56
@jchampagne looking at the API docs, it looks like you'd have to pass a properly formatted date string or an ISO-8601 formatted date string.

examples:
2013-10-13
2013-10-13T16:05:00.000

The basic format of ISO 8601 is yyyy-mm-ddThh:mm:ss[.mmm] where:

yyyy - four digit year
mm - two digit month (preceded with 0 if necessary)
dd - two digit date (preceded with 0 if necessary)
T - literal to separate the date from the time
hh - two digit hour in 24 hour format
mm - two digit minute
ss - two digit seconds
mmm - fractional seconds up to thousandths of a second

The API docs are vague about a "formatted time string" and so I'd stick with the ISO 8601 format.

**Comment by halr9000** [comment] 2013-10-24 20:02
Which URL are you looking at @jheiselman ? I can open a doc bug to have that page clarified. I'm nearly certain that unix epoch style will work, for example.

**Comment by jheiselman** [comment] 2013-10-25 15:34
@halr9000 

The URL is http://docs.splunk.com/Documentation/Splunk/6.0/RESTAPI/RESTsearch#POST_search.2Fjobs

The description for the earliest_time parameter is as follows:

```
Specify a time string. Sets the earliest (inclusive), respectively, time bounds for the search.
The time string can be either a UTC time (with fractional seconds), a relative time specifier (to now) or a formatted time string.

Compare to earliest_time parameter. Also see comment for the search_mode variable.
```

A time in ISO-8601 format is accounted for in an example further down the page. The relative time specifier is obvious (and an example is provided). The "formatted time string" however is not obvious. We've already accounted for ISO-8601. What other format's are acceptable? Windows users rarely interact with data in UTC or ISO-8601 format and their natural inclination is going to be using a time string acceptable to SQL Server or PowerShell.

**Comment by halr9000** [comment] 2013-10-25 17:29
Thanks @jheiselman. I just wrote a few paragraphs of feedback to our docs team about adding more references and to be sure to help with those coming from Windows platform. 

In addition, I've got a good answer for you that should work every time:

At the bottom of this doc page (http://docs.splunk.com/Documentation/Splunk/6.0/SearchReference/SearchTimeModifiers), I found a Unix time format string: %m/%d/%Y:%H:%M:%S

Here's how to get that from PowerShell:

``` powershell
get-date -UFormat '%m/%d/%Y:%H:%M:%S'
```

HTH

**Comment by jchampagne** [comment] 2013-10-28 15:57
Thanks for the info!  I can certainally use the ISO-8601 format.

**Comment by halr9000** [comment] 2013-10-28 16:10
Be careful with timezones, as this particular timestamp doesn't include a TZ indicator. You could use another format that does have a timezone, and Splunk would likely figure it out without blinking, but you should test it, of course. Also, be careful with Get-Date and timezones, because even though you can use -Format or -UFormat to output a timezone, or a "UTC" format, it does not CONVERT the time to the correct hour. e.g. if you are in -4, and get-date outputs "0400-0", meaning 4 AM UTC, it's actually local time 4 AM or midnight UTC, and Splunk will read that as "intended", and will be four hours off. To do the conversion, get the time, and then call the ToUniversalTime()  method on that object. Then you can use various string formatting techniques to spit that out in a format that works well for Splunk (of which there are many, but we don't make that very clear in docs).

``` powershell
PS C:\Users\hrottenberg> $t

Monday, October 28, 2013 12:06:57 PM


PS C:\Users\hrottenberg> $t.ToUniversalTime()

Monday, October 28, 2013 4:06:57 PM
```

**Comment by jheiselman** [comment] 2013-10-29 23:32
@halr9000 Actually, ISO 8601 does allow for a timezone designation. I just didn't include in my example as I assumed that @jchampagne would look up the standard.

https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators

**Comment by halr9000** [comment] 2014-04-21 15:57
Just merged a fix for this. Please test.

**Closed as completed by halr9000** 2014-04-21 15:57 UTC
